Repository DFE-Digital/education-benchmarking-and-insights, pull requests merged in 2025-08, with the labels that each got.

#2703 feat: ensures label clipping at appropriate length
  platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/builder.ts
  web/src/Web.App/AssetSrc/scss/_filter.scss
  web/src/Web.App/AssetSrc/scss/main.scss
Labels: javascript

#2705 feat: adds styles to filter box
  web/src/Web.App/AssetSrc/scss/_filter.scss
  web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
Labels: enhancement

#2706 feat: wire 'Show result as' filters into ItSpend API call
  web/src/Web.App/Controllers/SchoolComparisonItSpendController.cs
  web/src/Web.App/Domain/Charts/ChartDimensions.cs
  web/src/Web.App/Domain/Charts/SchoolComparisonItSpendHorizontalBarChartRequest.cs
  web/src/Web.App/ViewModels/SchoolComparisonItSpendViewModel.cs
  web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
Labels: enhancement, .NET

#2715 feat: normalise percentage values for SSR horizontal bar chart and resolve valueFormat from chartValueType
  platform/src/apis/Platform.Api.ChartRendering/src/assets/openapi.json
  platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/builder.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/worker.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/index.d.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/utils.ts
  platform/src/apis/Platform.Api.ChartRendering/src/openapi/horizontalBarChart/examples.ts
  platform/src/apis/Platform.Api.ChartRendering/tests/functions/utils.test.ts
  web/src/Web.App/Controllers/SchoolComparisonItSpendController.cs
  web/src/Web.App/Domain/Charts/Dimensions.cs
  web/src/Web.App/Domain/Charts/SchoolComparisonItSpendHorizontalBarChartRequest.cs
  web/src/Web.App/Domain/Charts/ValueType.cs
  web/src/Web.App/Infrastructure/Apis/ApiRequests/PostHorizontalBarChartRequest.cs
  web/src/Web.App/ViewModels/SchoolComparisonItSpendViewModel.cs
  web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
Labels: enhancement

#2725 chore: refactor worker pool to use single pool
  platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/function.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/worker.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/shared/pool.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/shared/worker.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/verticalBarChart/function.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/verticalBarChart/worker.ts
Labels: javascript, refactor

#2707 Doc/270042/cfr file generation process
  .vscode/settings.json
  documentation/financial-data-drop/cfr/0_Title.md
  documentation/financial-data-drop/cfr/1_Overview .md
  documentation/financial-data-drop/cfr/2_FactCFR.md
  documentation/financial-data-drop/cfr/3_DimPRU.md
  documentation/financial-data-drop/cfr/4_DimGeneralHospitalSchools.md
  documentation/financial-data-drop/cfr/5_DimGIAS.md
  documentation/financial-data-drop/cfr/6_DimSchoolCensus.md
  documentation/financial-data-drop/cfr/7_DimSEN.md
  documentation/financial-data-drop/cfr/8_DimSchoolWorkforceCensus.md
  documentation/financial-data-drop/cfr/9_SFB-FileGeneration.md
  documentation/financial-data-drop/cfr/image.png
  documentation/financial-data-drop/images/federated-school.png
  documentation/financial-data-drop/images/local-database-fact-and-dim-tables.png
  documentation/financial-data-drop/images/local-database-tables.png
  pipelines/documentation/build.yaml
Labels: documentation

#2728 feat: revised warning banner for postivie values only
  web/src/Web.App/Controllers/SchoolComparisonItSpendController.cs
  web/src/Web.App/Views/SchoolComparisonItSpend/Index.cshtml
  web/tests/Web.Integration.Tests/Pages/Schools/Comparison/WhenViewingComparisonItSpend.cs
Labels: enhancement, .NET

#2651 data ingestion test strategy
  documentation/quality-assurance/3_Test-strategy-data-ingestion.md
  documentation/quality-assurance/4_Test-Approach.md
  documentation/quality-assurance/5_Test-Plan.md
  documentation/quality-assurance/6_Security-Testing.md
  documentation/quality-assurance/7_Performance-Testing.md
  documentation/quality-assurance/8_Release-Comms.md
  documentation/quality-assurance/9_DSI-Test-Organisations.md
Labels: documentation

#2717 docs: adds initial documentation for metrics & measures
  documentation/operational/7_Metrics.md
  documentation/operational/metrics/001_service-availability.md
  documentation/operational/metrics/002_http-error-spike.md
  documentation/operational/metrics/003_high-memory-utilisation.md
  documentation/operational/metrics/004_high-cpu-utilisation.md
  documentation/operational/metrics/005_dependency-latency-regression.md
  documentation/operational/metrics/006_exception-rate-spike.md
  documentation/operational/metrics/007_failed-pipeline-messages.md
  documentation/operational/metrics/008_failed-request-spike.md
  documentation/operational/metrics/009_sustained-memory-growth.md
  documentation/operational/metrics/010_polly-429-warning-spike.md
  documentation/operational/metrics/011_polly-warning-volume-spike.md
  documentation/operational/metrics/012_response-latency-regression.md
  documentation/operational/metrics/013_bad-trace-ratio-degradation.md
  documentation/templates/metric.md
Labels: documentation

#2753 Updated failing API tests
  platform/tests/Platform.ApiTests/Data/TrustExpenditureActuals.json
  platform/tests/Platform.ApiTests/Data/TrustsExpenditureQuery.json
  platform/tests/Platform.ApiTests/Features/InsightExpenditure.feature
  platform/tests/Platform.ApiTests/Steps/InsightExpenditureSteps.cs
Labels: bug, .NET

#2754 Updated AAR code code for Grounds Maintenance Costs to `BAE170`
  web/src/Web.App/Domain/CostCodes.cs
  web/tests/Web.E2ETests/Features/School/CompareYourCosts.feature
  web/tests/Web.E2ETests/Features/Trust/CompareYourCosts.feature
  web/tests/Web.Tests/Domain/GivenASubCategoryCostCodes.cs
Labels: bug, .NET

#2755 docs: adds ADR 0015
  documentation/architecture/decisions/0013_DfE-Databricks.md
  documentation/architecture/decisions/0014-DfE-Databricks-data-out.md
  documentation/architecture/decisions/0015-chart-svg-generation.md
Labels: documentation

#2759 Removed `numeric` cell class from Pupils in tooltip table
  web/src/Web.App/AssetSrc/ts/components/school-chart-tooltip/SchoolChartTooltip.vue
Labels: enhancement

#2764 Bumped `platform` npm dependencies
  platform/src/apis/Platform.Api.ChartRendering/package-lock.json
  platform/src/apis/Platform.Api.ChartRendering/package.json
  platform/src/apis/Platform.Api.ChartRendering/src/functions/horizontalBarChart/function.ts
  platform/src/apis/Platform.Api.ChartRendering/src/functions/verticalBarChart/function.ts
Labels: dependencies, javascript

#2768 chore: update `Web.App` dependencies
  web/src/Web.App/package-lock.json
  web/src/Web.App/package.json
Labels: dependencies

#2769 chore: update `Web.Shutter` dependencies
  web/src/Web.Shutter/package-lock.json
  web/src/Web.Shutter/package.json
Labels: dependencies
