Repository DFE-Digital/education-benchmarking-and-insights, pull requests merged in 2025-07, with the labels that each got.

#2564 Removed orphaned Front Door ruleset
  web/terraform/README.md
  web/terraform/front-door.tf
Labels: terraform

#2569 Add pipeline run stats to CompletedPipelineRun table
  data-pipeline/src/pipeline/main.py
  data-pipeline/src/pipeline/pre_processing/ancillary/cdc.py
  data-pipeline/src/pipeline/pre_processing/ancillary/census.py
  data-pipeline/src/pipeline/pre_processing/ancillary/cfo.py
  data-pipeline/src/pipeline/pre_processing/ancillary/gias.py
  data-pipeline/src/pipeline/pre_processing/ancillary/high_exec_pay.py
  data-pipeline/src/pipeline/pre_processing/ancillary/ilr.py
  data-pipeline/src/pipeline/pre_processing/ancillary/ks2.py
  data-pipeline/src/pipeline/pre_processing/ancillary/ks4.py
  data-pipeline/src/pipeline/pre_processing/ancillary/sen.py
  data-pipeline/src/pipeline/stats_collector.py
  data-pipeline/tests/unit/test_stats_collector.py
Labels: enhancement

#2574 Wrapped SSR chart and stat boxes in `costs-chart-container` with `uuid` in order to include missing content in saved images
  web/src/Web.App/Views/SchoolSpending/CustomDataSsr.cshtml
  web/src/Web.App/Views/SchoolSpending/IndexSsr.cshtml
  web/src/Web.App/Views/Shared/Components/SchoolSpendingCostsSsr/Default.cshtml
Labels: bug, .NET

#2573 feat: updates to high executive pay chart
  front-end-components/index.html
  front-end-components/src/components/charts/utils.test.ts
  front-end-components/src/components/charts/utils.ts
  front-end-components/src/composed/dimensioned-chart/types.tsx
  front-end-components/src/composed/horizontal-bar-chart-wrapper/composed.tsx
  front-end-components/src/views/compare-your-trust/partials/accordion-sections/non-educational-support-staff.tsx
Labels: enhancement, javascript

#2581 chore: update `CommercialResources.json` following updates to d02 CommercialResources table
  platform/tests/Platform.ApiTests/Data/CommercialResources.json
Labels: .NET

#2587 chore: update platform nuget packages
  platform/Directory.Packages.props
  platform/src/abstractions/Platform.Cache/packages.lock.json
  platform/src/abstractions/Platform.Functions/packages.lock.json
  platform/src/abstractions/Platform.Search/packages.lock.json
  platform/src/abstractions/Platform.Sql/packages.lock.json
  platform/src/abstractions/Platform.Test/packages.lock.json
  platform/src/abstractions/tests/Platform.Cache.Tests/packages.lock.json
  platform/src/abstractions/tests/Platform.Domain.Tests/packages.lock.json
  platform/src/abstractions/tests/Platform.Functions.Tests/packages.lock.json
  platform/src/abstractions/tests/Platform.Search.Tests/packages.lock.json
  platform/src/abstractions/tests/Platform.Sql.Tests/packages.lock.json
  platform/src/apis/Platform.Api.Benchmark/packages.lock.json
  platform/src/apis/Platform.Api.Content/packages.lock.json
  platform/src/apis/Platform.Api.Establishment/packages.lock.json
  platform/src/apis/Platform.Api.Insight/packages.lock.json
  platform/src/apis/Platform.Api.LocalAuthorityFinances/packages.lock.json
  platform/src/apis/Platform.Api.NonFinancial/packages.lock.json
  platform/src/apis/Platform.Orchestrator/packages.lock.json
  platform/src/apis/Platform.UserDataCleanUp/packages.lock.json
  platform/src/search/Platform.Search.App/packages.lock.json
  platform/src/search/Platform.Search.Resources/packages.lock.json
  platform/tests/Platform.ApiTests/packages.lock.json
  platform/tests/Platform.Benchmark.Tests/packages.lock.json
  platform/tests/Platform.Content.Tests/packages.lock.json
  platform/tests/Platform.Establishment.Tests/packages.lock.json
  platform/tests/Platform.Insight.Tests/packages.lock.json
  platform/tests/Platform.LocalAuthorityFinances.Tests/packages.lock.json
  platform/tests/Platform.NonFinancial.Tests/packages.lock.json
  platform/tests/Platform.Orchestrator.Tests/packages.lock.json
Labels: dependencies, .NET

#2589 Bumped `prototype` node dependencies
  prototype/src/package-lock.json
  prototype/src/package.json
Labels: dependencies, javascript

#2597 feat: fixes table view
  front-end-components/src/components/charts/table-chart/component.tsx
Labels: enhancement, javascript

#2604 Added new feature flag `CfrItSpendBreakdown`
  web/README.md
  web/src/Web.App/Constants/FeatureFlags.cs
  web/src/Web.App/appsettings.Development.json
  web/terraform/README.md
  web/terraform/app-service.tf
  web/terraform/variables.tf
  web/tests/Web.Integration.Tests/BenchmarkingWebAppWebAppClient.cs
Labels: enhancement, terraform, .NET

#2606 Included `/web/src/Web.Shutter` in dependabot config
  .github/dependabot.yml
Labels: dependencies, ci/cd

#2643 Bumped `front-end` dependencies
  .github/dependabot.yml
  front-end-components/package-lock.json
  front-end-components/package.json
Labels: dependencies, javascript

#2652 Bumped `Web.App` dependencies
  web/Directory.Packages.props
  web/Web.sln
  web/src/Web.App/package-lock.json
  web/src/Web.App/package.json
  web/src/Web.App/packages.lock.json
  web/tests/Web.A11yTests/packages.lock.json
  web/tests/Web.E2ETests/packages.lock.json
  web/tests/Web.Integration.Tests/packages.lock.json
  web/tests/Web.Tests/packages.lock.json
Labels: dependencies, javascript, .NET

#2663 Remove finance tool `app-view-component` elements and associated assets
  web/src/Web.App/AssetSrc/images/areas-for-investigation.png
  web/src/Web.App/AssetSrc/images/benchmark-census.png
  web/src/Web.App/AssetSrc/images/central-services.png
  web/src/Web.App/AssetSrc/images/compare-your-costs.png
  web/src/Web.App/AssetSrc/images/curriculum-financial-planning.png
  web/src/Web.App/AssetSrc/images/forecast-risk.png
  web/src/Web.App/AssetSrc/images/high-needs.png
  web/src/Web.App/AssetSrc/images/side-by-side.png
  web/src/Web.App/AssetSrc/scss/main.scss
  web/src/Web.App/Views/Shared/Components/CustomDataFinanceTools/Default.cshtml
  web/src/Web.App/Views/Shared/Components/LocalAuthorityFinanceTools/Default.cshtml
  web/src/Web.App/Views/Shared/Components/SchoolFinanceTools/Default.cshtml
  web/src/Web.App/Views/Shared/Components/TrustFinanceTools/Default.cshtml
Labels: enhancement

#2669 feat: minor content update on high exec pay chart
  front-end-components/src/views/compare-your-trust/partials/accordion-sections/non-educational-support-staff.tsx
Labels: enhancement, javascript

#2672 feat: add IT spend views
  core-infrastructure/src/db/Core.Database/Views/026-ItSpendSchool.sql
Labels: enhancement
